services:
  web:
    build: .
    container_name: web_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    depends_on:
      - postgres
    volumes:
      - ./temporary/csv:/app/temporary/csv
      - ./temporary/pdf:/app/temporary/pdf
      - ./archive:/app/archive

  postgres:
    image: postgres:16
    container_name: p_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: