"""Adding ids

Revision ID: 2bba27286f84
Revises: a41129fe5a60
Create Date: 2025-10-31 10:10:17.087954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bba27286f84'
down_revision: Union[str, Sequence[str], None] = 'a41129fe5a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_personal_information')
    op.drop_table('employees_name')
    op.drop_table('employees_salary')
    op.drop_table('employees_cnp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees_salary',
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('bonus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('work', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees_cnp.cnp'], name=op.f('employees_salary_employee_id_fkey'))
    )
    op.create_table('employees_cnp',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_cnp_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cnp', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='employees_cnp_pkey'),
    sa.UniqueConstraint('cnp', name='employees_cnp_cnp_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('employees_name',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees_cnp.cnp'], name=op.f('employees_name_employee_id_fkey'))
    )
    op.create_table('employees_personal_information',
    sa.Column('position', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_of_hire', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees_cnp.cnp'], name=op.f('employees_personal_information_employee_id_fkey'))
    )
    # ### end Alembic commands ###
